spring:
  application:
    name: apollo-portal
  profiles:
    active: auth
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192 # limit query plan cache max size
  datasource:
    #MySQL配置
    url:  jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
    username: root
    password: 123456

server:
  port: 8070
  compression:
    enabled: true
  tomcat:
    use-relative-redirects: true

logging:
  file: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP








