spring:
  application:
    name: apollo-adminservice
  profiles:
    active: github

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/2019-12-28/apollo-adminservice.log
